desc = '''
Module that provides a header-only library that contains an n-d matrix class and fourth-, second-,
and first-order tensors (a.k.a. vectors) in C++. Each of these classes has a direct interface to
NumPy through pybind11.

The purpose of this Python package is to simplify the installation and distribution of modules that
depend on cppmat. There is no direct use for Python.
'''

import re, os
from setuptools import setup

header = open('src/cppmat/cppmat.h','r').read()
world  = re.split(r'(.*)(\#define CPPMAT_WORLD_VERSION\ )([0-9]+)(.*)',header)[3]
major  = re.split(r'(.*)(\#define CPPMAT_MAJOR_VERSION\ )([0-9]+)(.*)',header)[3]
minor  = re.split(r'(.*)(\#define CPPMAT_MINOR_VERSION\ )([0-9]+)(.*)',header)[3]

__version__ = '.'.join([world,major,minor])

setup(
  name             = 'cppmat',
  description      = 'Multidimensional arrays and tensors in C++',
  long_description = desc,
  keywords         = 'C++, C++11, Python bindings, pybind11',
  version          = __version__,
  license          = 'MIT',
  author           = 'Tom de Geus',
  author_email     = 'tom@geus.me',
  url              = 'https://github.com/tdegeus/cppmat',
  packages         = ['cppmat'],
  headers          = [
    'src/cppmat/cppmat.h',
    'src/cppmat/private.cpp',
    'src/cppmat/private.h',
    'src/cppmat/stl.cpp',
    'src/cppmat/stl.h',
    'src/cppmat/fix_cartesian.cpp',
    'src/cppmat/fix_cartesian.h',
    'src/cppmat/fix_cartesian_2.cpp',
    'src/cppmat/fix_cartesian_3.cpp',
    'src/cppmat/fix_cartesian_tensor2.cpp',
    'src/cppmat/fix_cartesian_tensor2.h',
    'src/cppmat/fix_cartesian_tensor2d.cpp',
    'src/cppmat/fix_cartesian_tensor2d.h',
    'src/cppmat/fix_cartesian_tensor2s.cpp',
    'src/cppmat/fix_cartesian_tensor2s.h',
    'src/cppmat/fix_cartesian_tensor4.cpp',
    'src/cppmat/fix_cartesian_tensor4.h',
    'src/cppmat/fix_cartesian_vector.cpp',
    'src/cppmat/fix_cartesian_vector.h',
    'src/cppmat/fix_diagonal_matrix.cpp',
    'src/cppmat/fix_diagonal_matrix.h',
    'src/cppmat/fix_misc_matrix.cpp',
    'src/cppmat/fix_misc_matrix.h',
    'src/cppmat/fix_periodic_array.cpp',
    'src/cppmat/fix_periodic_array.h',
    'src/cppmat/fix_periodic_matrix.cpp',
    'src/cppmat/fix_periodic_matrix.h',
    'src/cppmat/fix_periodic_vector.cpp',
    'src/cppmat/fix_periodic_vector.h',
    'src/cppmat/fix_regular_array.cpp',
    'src/cppmat/fix_regular_array.h',
    'src/cppmat/fix_regular_matrix.cpp',
    'src/cppmat/fix_regular_matrix.h',
    'src/cppmat/fix_regular_vector.cpp',
    'src/cppmat/fix_regular_vector.h',
    'src/cppmat/fix_symmetric_matrix.cpp',
    'src/cppmat/fix_symmetric_matrix.h',
    'src/cppmat/map_cartesian_tensor2.cpp',
    'src/cppmat/map_cartesian_tensor2.h',
    'src/cppmat/map_cartesian_tensor2d.cpp',
    'src/cppmat/map_cartesian_tensor2d.h',
    'src/cppmat/map_cartesian_tensor2s.cpp',
    'src/cppmat/map_cartesian_tensor2s.h',
    'src/cppmat/map_cartesian_tensor4.cpp',
    'src/cppmat/map_cartesian_tensor4.h',
    'src/cppmat/map_cartesian_vector.cpp',
    'src/cppmat/map_cartesian_vector.h',
    'src/cppmat/map_diagonal_matrix.cpp',
    'src/cppmat/map_diagonal_matrix.h',
    'src/cppmat/map_periodic_array.cpp',
    'src/cppmat/map_periodic_array.h',
    'src/cppmat/map_periodic_matrix.cpp',
    'src/cppmat/map_periodic_matrix.h',
    'src/cppmat/map_periodic_vector.cpp',
    'src/cppmat/map_periodic_vector.h',
    'src/cppmat/map_regular_array.cpp',
    'src/cppmat/map_regular_array.h',
    'src/cppmat/map_regular_matrix.cpp',
    'src/cppmat/map_regular_matrix.h',
    'src/cppmat/map_regular_vector.cpp',
    'src/cppmat/map_regular_vector.h',
    'src/cppmat/map_symmetric_matrix.cpp',
    'src/cppmat/map_symmetric_matrix.h',
    'src/cppmat/var_cartesian.cpp',
    'src/cppmat/var_cartesian.h',
    'src/cppmat/var_cartesian_tensor2.cpp',
    'src/cppmat/var_cartesian_tensor2.h',
    'src/cppmat/var_cartesian_tensor2d.cpp',
    'src/cppmat/var_cartesian_tensor2d.h',
    'src/cppmat/var_cartesian_tensor2s.cpp',
    'src/cppmat/var_cartesian_tensor2s.h',
    'src/cppmat/var_cartesian_tensor4.cpp',
    'src/cppmat/var_cartesian_tensor4.h',
    'src/cppmat/var_cartesian_vector.cpp',
    'src/cppmat/var_cartesian_vector.h',
    'src/cppmat/var_diagonal_matrix.cpp',
    'src/cppmat/var_diagonal_matrix.h',
    'src/cppmat/var_misc_matrix.cpp',
    'src/cppmat/var_misc_matrix.h',
    'src/cppmat/var_periodic_array.cpp',
    'src/cppmat/var_periodic_array.h',
    'src/cppmat/var_periodic_matrix.cpp',
    'src/cppmat/var_periodic_matrix.h',
    'src/cppmat/var_periodic_vector.cpp',
    'src/cppmat/var_periodic_vector.h',
    'src/cppmat/var_regular_array.cpp',
    'src/cppmat/var_regular_array.h',
    'src/cppmat/var_regular_matrix.cpp',
    'src/cppmat/var_regular_matrix.h',
    'src/cppmat/var_regular_vector.cpp',
    'src/cppmat/var_regular_vector.h',
    'src/cppmat/var_symmetric_matrix.cpp',
    'src/cppmat/var_symmetric_matrix.h',
    'src/cppmat/pybind11.h',
    'src/cppmat/pybind11_fix_cartesian_tensor2.h',
    'src/cppmat/pybind11_fix_cartesian_tensor2d.h',
    'src/cppmat/pybind11_fix_cartesian_tensor2s.h',
    'src/cppmat/pybind11_fix_cartesian_tensor4.h',
    'src/cppmat/pybind11_fix_cartesian_vector.h',
    'src/cppmat/pybind11_fix_diagonal_matrix.h',
    'src/cppmat/pybind11_fix_periodic_array.h',
    'src/cppmat/pybind11_fix_periodic_matrix.h',
    'src/cppmat/pybind11_fix_periodic_vector.h',
    'src/cppmat/pybind11_fix_regular_array.h',
    'src/cppmat/pybind11_fix_regular_matrix.h',
    'src/cppmat/pybind11_fix_regular_vector.h',
    'src/cppmat/pybind11_fix_symmetric_matrix.h',
    'src/cppmat/pybind11_var_cartesian_tensor2.h',
    'src/cppmat/pybind11_var_cartesian_tensor2d.h',
    'src/cppmat/pybind11_var_cartesian_tensor2s.h',
    'src/cppmat/pybind11_var_cartesian_tensor4.h',
    'src/cppmat/pybind11_var_cartesian_vector.h',
    'src/cppmat/pybind11_var_diagonal_matrix.h',
    'src/cppmat/pybind11_var_periodic_array.h',
    'src/cppmat/pybind11_var_periodic_matrix.h',
    'src/cppmat/pybind11_var_periodic_vector.h',
    'src/cppmat/pybind11_var_regular_array.h',
    'src/cppmat/pybind11_var_regular_matrix.h',
    'src/cppmat/pybind11_var_regular_vector.h',
    'src/cppmat/pybind11_var_symmetric_matrix.h',
  ],
  install_requires = ['pybind11>=2.2.0'],
)

